Update terraform setup

diff --git a/.github/actions/setup-terraform.yml b/.github/actions/setup-terraform.yml
--- a/.github/actions/setup-terraform.yml
+++ b/.github/actions/setup-terraform.yml
@@ -1,20 +1,25 @@
 name: 'Terraform Setup and Validate'
 
-jobs:
-  terraform-setup:
-    steps:
-    - name: 'Check and set Terraform version'
-      run: |
-        if [[ ! "${{ inputs.terraform-version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Error: terraform-version input must be in the format v0-9.0-9.0-9 or be blank"
-          exit 1
-        else
-          tfenv use ${{ inputs.terraform-version }}
-        fi
-      if: ${{ inputs.terraform-version != '' }}
+inputs:
+  terraform-version:
+    required: false
+    type: string
 
-    - name: 'Terraform Init'
-      run: terraform init
+runs:
+ using: "composite"
+  steps:
+  - name: 'Check and set Terraform version'
+    run: |
+      if [[ ! "${{ inputs.terraform-version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        echo "Error: terraform-version input must be in the format v0-9.0-9.0-9 or be blank"
+        exit 1
+      else
+        tfenv use ${{ inputs.terraform-version }}
+      fi
+    if: ${{ inputs.terraform-version != '' }}
 
-    - name: 'Terraform Validate'
-      run: terraform validate
+  - name: 'Terraform Init'
+    run: terraform init
+
+  - name: 'Terraform Validate'
+    run: terraform validate
