Started Terraform folder handling

diff --git a/.github/workflows/terraform-ci.yml b/.github/workflows/terraform-ci.yml
--- a/.github/workflows/terraform-ci.yml
+++ b/.github/workflows/terraform-ci.yml
@@ -12,16 +12,61 @@ permissions:
   packages: read
 
 jobs:
+  pre-configuration:
+    runs-on: ubuntu-latest
+
+    outputs:
+      core_folders: ${{ steps.find-folders.outputs.core_folders }}
+      app_folders: ${{ steps.find-folders.outputs.app_folders }}
+
+    steps:
+    - name: 'Checkout Repository'
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ github.head_ref || github.ref_name }}
+
+    - name: 'Find Terraform Folders'
+      id: find-folders
+      run: |
+        FOLDERS=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u)
+        CORE_FOLDERS=$(echo "$FOLDERS" | grep -E '^./core-services/' | sort -u)
+        APP_FOLDERS=$(echo "$FOLDERS" | grep -E '^./applications/' | sort -u)
+        echo "core_folders=$CORE_FOLDERS" >> "$GITHUB_OUTPUT"
+        echo "app_folders=$APP_FOLDERS" >> "$GITHUB_OUTPUT"
+
+    - name: 'Check Core Services Folders'
+      run: |
+        INVALID_CORE_FOLDERS=$(echo "${CORE_FOLDERS}" | grep -Ev '^./core-services/[0-9]')
+        if [ -n "$INVALID_CORE_FOLDERS" ]; then
+          echo "All core services folders must be named with a number prefix"
+          echo "Invalid Core Services Folders: $INVALID_CORE_FOLDERS"
+          exit 1
+        fi
+
+    - name: 'Check Application Folders'
+      run: |
+        INVALID_APP_FOLDERS=$(echo "${APP_FOLDERS}" | grep -Ev '^./applications/[0-9]')
+        if [ -n "$INVALID_APP_FOLDERS" ]; then
+          echo "All application folders must be named with a number prefix"
+          echo "Invalid Application Folders: $INVALID_APP_FOLDERS"
+          exit 1
+        fi
+
+    - name: 'Terraform Folders'
+      run: |
+        echo "This action will use these Terraform folders: ${{ steps.find-folders.outputs.folders }}"
+
   terraform-formatting:
     container: 
       image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
     runs-on: ubuntu-latest
+    needs: [ pre-configuration ]
     
     steps:
     - name: 'Checkout Repository'
       uses: actions/checkout@v4
       with:
-        ref: ${{ github.head_ref || github.ref_name }} 
+        ref: ${{ github.head_ref || github.ref_name }}
 
     - name: 'Setup Terraform'
       uses: ukhsa-internal/devops-github-reusable-workflows/.github/actions/setup-terraform@main
@@ -60,11 +105,13 @@ jobs:
     container: 
       image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
     runs-on: ubuntu-latest
-    needs: [ terraform-formatting ] 
+    needs: [ pre-configuration, terraform-formatting ] 
     
     steps:
     - name: 'Checkout Repository'
       uses: actions/checkout@v4
+      with:
+        ref: ${{ github.head_ref || github.ref_name }}
 
     - name: 'Setup Terraform'
       uses: ukhsa-internal/devops-github-reusable-workflows/.github/actions/setup-terraform@main
@@ -78,11 +125,13 @@ jobs:
     container: 
       image: ghcr.io/ukhsa-internal/devops-terraform-ci:latest
     runs-on: ubuntu-latest
-    needs: [ terraform-formatting, terraform-checks ]
+    needs: [ pre-configuration, terraform-formatting, terraform-checks ]
     
     steps:
     - name: 'Checkout Repository'
       uses: actions/checkout@v4
+      with:
+        ref: ${{ github.head_ref || github.ref_name }}
 
     - name: 'Setup Terraform'
       uses: ukhsa-internal/devops-github-reusable-workflows/.github/actions/setup-terraform@main
