Add missing needs dependency (#42)
#major

- Added logic for filtering matrix objects based on whether there are planned changes or not.
- Added sequential apply workflow for use of initial setup of environments.
- Fixed the post deployment QA workflow.

diff --git a/.github/workflows/terraform-core.yml b/.github/workflows/terraform-core.yml
--- a/.github/workflows/terraform-core.yml
+++ b/.github/workflows/terraform-core.yml
@@ -24,8 +24,8 @@ on:
         type: string
         default: "apply"
         description: "Which Terraform action to run. 'apply' or 'destroy'"
-      directories:
-        description: "The list of Terraform stacks to run Terraform in"
+      stack_config:
+        description: "A detailed matrix containing the Terraform stack configuration and dependencies"
         required: true
         type: string
       max_parallel:
@@ -53,11 +53,6 @@ on:
         type: boolean
         default: false
         description: "Download an artifact containing an existing Terraform plan created by a previous run. Incompatible with upload_plan"
-      runner_label:
-        required: false
-        type: string
-        default: "ubuntu-latest"
-        description: "Specifies a targetted runner for the job. Use \"self-hosted\" if you've configured a self hosted runner, otherwise leave as the default."
     
     secrets:
       AWS_ROLE_NAME:
@@ -95,15 +90,15 @@ on:
 
 jobs:
   initialise:
-    name: "Initialise and run Terraform for ${{ matrix.directory }}"
-    runs-on: ${{ inputs.runner_label }}
+    name: "Initialise and run Terraform for ${{ matrix.stack.directory }}"
+    runs-on: "${{ matrix.stack.runner_label }}"
     environment: ${{ inputs.environment_name }}
     defaults:
       run:
         shell: bash
     strategy:
       matrix:
-        directory: "${{ fromJSON(inputs.directories) }}"
+        stack: "${{ fromJSON(inputs.stack_config) }}"
       max-parallel: ${{ inputs.max_parallel }}
     steps:
       - name: Checkout code
@@ -114,7 +109,7 @@ jobs:
           ssh-key: ${{ secrets.REPO_SSH_DEPLOY_KEY }}
 
       - name: Export variables
-        run: echo "state_name=$(basename ${{ matrix.directory }})" >> $GITHUB_ENV
+        run: echo "state_name=$(basename ${{ matrix.stack.directory }})" >> $GITHUB_ENV
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
@@ -146,7 +141,7 @@ jobs:
 
       - name: Copy required files from root directory
         env:
-          DIRECTORY: "${{ matrix.directory }}"
+          DIRECTORY: "${{ matrix.stack.directory }}"
         run: |
           files_to_copy=("providers.tf" "terraform.tf")
 
@@ -160,27 +155,27 @@ jobs:
           done
 
       - name: Find Terraform version
-        uses: UKHSA-Internal/devops-github-actions/.github/actions/parse-terraform-version@main
+        uses: UKHSA-Internal/devops-github-actions/.github/actions/parse-terraform-version@v0.7.0
         id: terraform_version
         with:
-          tf_file: "${{ matrix.directory }}/terraform.tf"
+          tf_file: "${{ matrix.stack.directory }}/terraform.tf"
 
       - name: Setup Terraform for self-hosted runner
-        if: ${{ inputs.runner_label == 'self-hosted' }}
+        if: ${{ contains(matrix.stack.runner_label, 'self-hosted') }}
         run: |
           echo "Terraform Version: ${{ steps.terraform_version.outputs.tf_version }}" 
           tfenv use ${{ steps.terraform_version.outputs.tf_version }}
           terraform --version
-        working-directory: ${{ matrix.directory }}
+        working-directory: ${{ matrix.stack.directory }}
 
       - name: Setup Terraform for GHE runner
-        if: ${{ inputs.runner_label != 'self-hosted' }}
+        if: ${{ !contains(matrix.stack.runner_label, 'self-hosted') }}
         uses: hashicorp/setup-terraform@v3
         with:
           terraform_version: "${{ steps.terraform_version.outputs.tf_version }}"
 
       - name: Determine Backend Type
-        working-directory: "${{ matrix.directory }}"
+        working-directory: "${{ matrix.stack.directory }}"
         id: backend
         run: |
           backend_type=$(grep -oP 'backend\s+"?\K[^"\s]+' ./backend.tf)
@@ -203,13 +198,13 @@ jobs:
           echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
 
       - name: Terraform Init with AWS S3 Backend
-        working-directory: "${{ matrix.directory }}"
+        working-directory: "${{ matrix.stack.directory }}"
         if: ${{ steps.backend.outputs.backend_type == 's3' }}
         env:
           AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID }}"
           AWS_REGION: "${{ inputs.aws_region }}"
           ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
-          DIRECTORY: "${{ matrix.directory }}"
+          DIRECTORY: "${{ matrix.stack.directory }}"
         run: |
           s3_key="${ENVIRONMENT_NAME}"/"$state_name"/terraform.tfstate
           dynamodb_table=${AWS_REGION}-state-locks
@@ -221,10 +216,10 @@ jobs:
 
       - name: Terraform Init with Azure Backend
         if: ${{ steps.backend.outputs.backend_type == 'azurerm' }}
-        working-directory: "${{ matrix.directory }}"
+        working-directory: "${{ matrix.stack.directory }}"
         env:
           ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
-          DIRECTORY: "${{ matrix.directory }}"
+          DIRECTORY: "${{ matrix.stack.directory }}"
           ARM_USE_OIDC: true
           ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
           ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
@@ -236,11 +231,11 @@ jobs:
           terraform init \
             -backend-config=storage_account_name="${storage_account_name}" \
             -backend-config=container_name="$container_name" \
-            -backend-config=key="${ENVIRONMENT_NAME}"/"$state_name"/terraform.tfstate \
+            -backend-config=key=$ENVIRONMENT_NAME/"$state_name"/terraform.tfstate \
             -backend-config=resource_group_name="${{ secrets.AZURE_RESOURCE_GROUP_NAME }}"
 
       - name: Check if the state file is empty
-        working-directory: "${{ matrix.directory }}"
+        working-directory: "${{ matrix.stack.directory }}"
         id: state_empty
         shell: bash
         env:
@@ -267,7 +262,7 @@ jobs:
         id: variables
         if: steps.state_empty.outputs.skip_workflow == 'false'
         env:
-          DIRECTORY: "${{ matrix.directory }}"
+          DIRECTORY: "${{ matrix.stack.directory }}"
           ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
         run: |
           find_app_var_files() {
@@ -313,11 +308,13 @@ jobs:
         id: download_plan
         if: ( inputs.download_existing_plan == true && steps.state_empty.outputs.state_empty == 'false' )
         with:
-          name: "tfplan-${{ env.state_name }}"
-          path: ${{ matrix.directory }}
+          name: "${{ env.state_name }}-artefacts"
+          path: ${{ matrix.stack.directory }}
 
       - name: Terraform Plan
-        working-directory: "${{ matrix.directory }}"
+        id: tf_plan
+        working-directory: "${{ matrix.stack.directory }}"
+        continue-on-error: true
         if: steps.download_plan.conclusion == 'skipped' && steps.state_empty.outputs.skip_workflow == 'false' 
         env:
           ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
@@ -329,25 +326,93 @@ jobs:
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           TERRAFORM_ACTION: ${{ inputs.terraform_action }}
         run: |
+          # Required, otherwise GitHub will exit immediately when the tf plan exit code is non-zero (2 = changes)
+          set +e 
+
           if [[ "$TERRAFORM_ACTION" == "destroy" ]]; then
-            terraform plan -lock-timeout=5m -destroy -no-color -input=false -out=tfplan -compact-warnings ${TERRAFORM_VARIABLES}
+            terraform plan -lock-timeout=5m -destroy -no-color -input=false -out=tfplan -detailed-exitcode -compact-warnings ${TERRAFORM_VARIABLES}
           else
-            terraform plan -lock-timeout=5m -no-color -input=false -out=tfplan -compact-warnings ${TERRAFORM_VARIABLES}
+            terraform plan -lock-timeout=5m -no-color -input=false -out=tfplan -detailed-exitcode -compact-warnings ${TERRAFORM_VARIABLES}
           fi
+          
+          terraform_exit_code=$?
+
+          echo "Terraform exit code: $terraform_exit_code"
+          echo "terraform_exit_code=$terraform_exit_code" >> $GITHUB_OUTPUT
+
           terraform show -json tfplan | jq > tfplan.json
 
-      - name: Upload Terraform Plan
+          # If no changes are required, we can skip subsequent steps for this stack.
+          if [ $terraform_exit_code -eq 0 ]; then
+            # If there are resources to be destroyed, the -detailed-exitcode returned is 0, despite changes being present.
+            # Additional logic required to inspect the tfplan.json file for if any destroy actions are present.
+            destroy_count=$(jq '[.resource_changes[] | select(.change.actions | index("delete"))] | length' tfplan.json)
+            echo "Destroy count: $destroy_count"
+            if [ "$destroy_count" -gt 0 ]; then
+                planned_changes=true
+            else
+                planned_changes=false
+            fi
+          elif [ $terraform_exit_code -eq 2 ]; then
+              planned_changes=true
+          else
+              exit $terraform_exit_code
+          fi
+          
+          echo "planned_changes=$planned_changes" >> $GITHUB_OUTPUT
+          
+      - name: Check Terraform plan exit code
+        if: steps.tf_plan.conclusion == 'success' || steps.tf_plan.conclusion == 'failure'
+        env:
+          terraform_exit_code: "${{ steps.tf_plan.outputs.terraform_exit_code }}"
+        run: |
+          # Separate step required otherwise GitHub will exit on non-zero exit code.
+          if [ $terraform_exit_code -eq 1 ]; then
+            echo "Terraform encountered an error. Exiting workflow."
+            exit 1
+          fi
+
+      - name: Update stack matrix
+        working-directory: "${{ matrix.stack.directory }}"
+        run: |
+          # If the tf_plan step was skipped because of no state, persist the stack configuration with planned_changes.
+          if [ "${{ steps.tf_plan.conclusion }}" == "skipped" ]; then
+            planned_changes="${{ matrix.stack.planned_changes }}"
+          else
+            planned_changes="${{ steps.tf_plan.outputs.planned_changes }}"
+          fi
+
+          echo "runner_label is: ${{ matrix.stack.runner_label }}"
+
+          jq -n \
+            --arg dir "${{ matrix.stack.directory }}" \
+            --argjson runner_label '${{ toJSON(matrix.stack.runner_label) }}' \
+            --argjson planned_changes "$planned_changes" \
+            --argjson order "${{ matrix.stack.order }}" \
+            '{
+              directory: $dir,
+              runner_label: ($runner_label | if type=="array" then . else [.] end),
+              planned_changes: $planned_changes,
+              order: $order
+            }' \
+            > updated_matrix.json
+
+          cat updated_matrix.json
+
+      - name: Upload Terraform Plan and matrix
         uses: actions/upload-artifact@v4
-        if: inputs.upload_plan && steps.state_empty.outputs.skip_workflow == 'false'
+        if: ${{ inputs.upload_plan }}
         with:
-          name: "tfplan-${{ env.state_name }}"
-          path: "${{ matrix.directory }}/tfplan*"
-          if-no-files-found: error
+          name: "${{ env.state_name }}-artefacts"
+          path: |
+            ${{ matrix.stack.directory }}/tfplan*
+            ${{ matrix.stack.directory }}/updated_matrix.json
+          if-no-files-found: warn
           compression-level: 1
           retention-days: 1
   
       - name: Terraform Destructive Actions Check
-        working-directory: "${{ matrix.directory }}"
+        working-directory: "${{ matrix.stack.directory }}"
         if: >-
           ${{ ( inputs.destructive_action_check ||
             inputs.environment_name == 'pre' || 
@@ -362,8 +427,10 @@ jobs:
           fi
 
       - name: Terraform Apply
-        if: inputs.execute_terraform_plan && steps.state_empty.outputs.skip_workflow == 'false'
-        working-directory: "${{ matrix.directory }}"
+        if: >-
+          ${{ inputs.execute_terraform_plan &&
+          steps.state_empty.outputs.skip_workflow == 'false' }}
+        working-directory: "${{ matrix.stack.directory }}"
         env:
           ENVIRONMENT_NAME: "${{ inputs.environment_name }}"
           TERRAFORM_VARIABLES: "${{ steps.variables.outputs.tf_vars }}"
